/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author LUCYLEONOR
 */
public class Viaje extends javax.swing.JFrame {

    /**
     * Creates new form Viaje
     */
    public Viaje() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNP = new javax.swing.JTextField();
        txtND = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        lblT = new javax.swing.JLabel();
        cmdCalcular = new javax.swing.JButton();
        cmdRestaurar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Agencia De Viaje");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Agencia de viaje");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Núm. Personas");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Núm. Dias");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, -1, -1));

        txtNP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNPKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNPKeyTyped(evt);
            }
        });
        jPanel1.add(txtNP, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 70, -1));

        txtND.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNDKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNDKeyTyped(evt);
            }
        });
        jPanel1.add(txtND, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 70, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Total a Pagar");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, -1, -1));

        lblT.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(lblT, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 120, 30));

        cmdCalcular.setText("Calcular");
        cmdCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCalcularActionPerformed(evt);
            }
        });
        jPanel1.add(cmdCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, -1, -1));

        cmdRestaurar.setText("Restaurar");
        cmdRestaurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdRestaurarActionPerformed(evt);
            }
        });
        jPanel1.add(cmdRestaurar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCalcularActionPerformed

         if (txtND.getText().trim().isEmpty() && txtNP.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "No Ingresó Los Datos Solicitados", "ERROR", JOptionPane.ERROR_MESSAGE);
                txtNP.requestFocusInWindow();
            } else if (txtND.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "No Ingresó El Numero De Días", "ERROR", JOptionPane.ERROR_MESSAGE);
                txtND.requestFocusInWindow();
            } else if (txtNP.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "No Ingresó El Numero De Personas", "ERROR", JOptionPane.ERROR_MESSAGE);
                txtNP.requestFocusInWindow();
            } else if (txtND.getText().equalsIgnoreCase("0")) {
                JOptionPane.showMessageDialog(this, "El Numero De Días Debe Ser Superior A 0", "ERROR", JOptionPane.ERROR_MESSAGE);
                txtND.requestFocusInWindow();
                txtND.selectAll();
            } else if (txtNP.getText().equalsIgnoreCase("0")) {
                JOptionPane.showMessageDialog(this, "El Numero De Personas Debe Ser Superior A 0", "ERROR", JOptionPane.ERROR_MESSAGE);
                txtNP.requestFocusInWindow();
                txtNP.selectAll();
            }
            else{
            String r;
            int np;
            double nd, t;

            nd = Double.parseDouble(txtND.getText());
            np = Integer.parseInt(txtNP.getText());

            t = ((25000 * nd) * np) * 1.12;

            r = String.valueOf(t);
            lblT.setText("$ " + r);
            }
    }//GEN-LAST:event_cmdCalcularActionPerformed

    private void cmdRestaurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdRestaurarActionPerformed

        txtND.setText("");
        txtNP.setText("");
        lblT.setText("");
        txtNP.requestFocusInWindow();


    }//GEN-LAST:event_cmdRestaurarActionPerformed

    private void txtNPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNPKeyTyped
        char c = evt.getKeyChar();

        if (!Character.isDigit(c) && evt.getKeyCode() == KeyEvent.VK_ENTER) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtNPKeyTyped

    private void txtNDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNDKeyTyped
        char c = evt.getKeyChar();

        if (!Character.isDigit(c) && evt.getKeyCode() == KeyEvent.VK_ENTER) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtNDKeyTyped

    private void txtNPKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNPKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

                if (txtND.getText().trim().isEmpty() && txtNP.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "No Ingresó Los Datos Solicitados", "ERROR", JOptionPane.ERROR_MESSAGE);
                txtNP.requestFocusInWindow();
            } else if (txtND.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "No Ingresó El Numero De Días", "ERROR", JOptionPane.ERROR_MESSAGE);
                txtND.requestFocusInWindow();
            } else if (txtNP.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "No Ingresó El Numero De Personas", "ERROR", JOptionPane.ERROR_MESSAGE);
                txtNP.requestFocusInWindow();
            } else if (txtND.getText().equalsIgnoreCase("0")) {
                JOptionPane.showMessageDialog(this, "El Numero De Días Debe Ser Superior A 0", "ERROR", JOptionPane.ERROR_MESSAGE);
                txtND.requestFocusInWindow();
                txtND.selectAll();
            } else if (txtNP.getText().equalsIgnoreCase("0")) {
                JOptionPane.showMessageDialog(this, "El Numero De Personas Debe Ser Superior A 0", "ERROR", JOptionPane.ERROR_MESSAGE);
                txtNP.requestFocusInWindow();
                txtNP.selectAll();
            }
            else{
            String r;
            int np;
            double nd, t;

            nd = Double.parseDouble(txtND.getText());
            np = Integer.parseInt(txtNP.getText());

            t = ((25000 * nd) * np) * 1.12;

            r = String.valueOf(t);
            lblT.setText("$ " + r);
            }
        }
    }//GEN-LAST:event_txtNPKeyPressed

    private void txtNDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNDKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

                if (txtND.getText().trim().isEmpty() && txtNP.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "No Ingresó Los Datos Solicitados", "ERROR", JOptionPane.ERROR_MESSAGE);
                txtNP.requestFocusInWindow();
            } else if (txtND.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "No Ingresó El Numero De Días", "ERROR", JOptionPane.ERROR_MESSAGE);
                txtND.requestFocusInWindow();
            } else if (txtNP.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "No Ingresó El Numero De Personas", "ERROR", JOptionPane.ERROR_MESSAGE);
                txtNP.requestFocusInWindow();
            } else if (txtND.getText().equalsIgnoreCase("0")) {
                JOptionPane.showMessageDialog(this, "El Numero De Días Debe Ser Superior A 0", "ERROR", JOptionPane.ERROR_MESSAGE);
                txtND.requestFocusInWindow();
                txtND.selectAll();
            } else if (txtNP.getText().equalsIgnoreCase("0")) {
                JOptionPane.showMessageDialog(this, "El Numero De Personas Debe Ser Superior A 0", "ERROR", JOptionPane.ERROR_MESSAGE);
                txtNP.requestFocusInWindow();
                txtNP.selectAll();
            }
            else{
            String r;
            int np;
            double nd, t;

            nd = Double.parseDouble(txtND.getText());
            np = Integer.parseInt(txtNP.getText());

            t = ((25000 * nd) * np) * 1.12;

            r = String.valueOf(t);
            lblT.setText("$ " + r);
            }
        }
    }//GEN-LAST:event_txtNDKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Viaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Viaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Viaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Viaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Viaje().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdCalcular;
    private javax.swing.JButton cmdRestaurar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblT;
    private javax.swing.JTextField txtND;
    private javax.swing.JTextField txtNP;
    // End of variables declaration//GEN-END:variables
}
